# Generated by Django 4.0.5 on 2022-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField(max_length=2)),
                ('city', models.CharField(max_length=15)),
                ('stdclass', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
